apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: coit-frontend
spec:
  maxReplicas: 20
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: coit-frontend
  targetCPUUtilizationPercentage: 60