apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: coit-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: coit-frontend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

