apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coit-frontend
  namespace: customer1    
spec:
  ingressClassName: nginx
  rules:
  - host: "customer1.basilportfolio.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: coit-frontend-lb
            port:
              number: 80
