apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - coit-frontend
  - sumaimagejava2  
  - sumapython

replicas:
- name: coit-frontend
  count: 3
- name: sumaimagejava2
  count: 3
- name: sumapython
  count: 3




namespace: suma
