FROM maven:3.8.4-amazoncorretto-8 AS build
WORKDIR /usr/app
COPY . /usr/app
RUN mvn install

FROM gcr.io/distroless/java11-debian11
# Environment Variable that defines the endpoint of sentiment-analysis python api.
ENV SA_LOGIC_API_URL http://localhost:5000
EXPOSE 8080
CMD ["java", "-jar", "sentiment-analysis-web-0.0.2-SNAPSHOT.jar", "--sa.logic.api.url=${SA_LOGIC_API_URL}"]
COPY --from=build /usr/app/target/sentiment-analysis-web-0.0.2-SNAPSHOT.jar /
