apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../coit-frontend-deployment.yaml
  - ../../service-coit-frontend-lb.yaml

replicas:
- name: coit-frontend 
  count: 3

namespace: default
