apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../coit-backend1
  - ../../coit-frontend

replicas:
- name: coit-backend1
  count: 5
- name: coit-frontend 
  count: 10

namespace: production