apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../coit-frontend

replicas:
- name: coit-frontend 
  count: 3

images:
- name: coitlearning/coit-frontend
  newName: coitlearning/coit-frontend
  newTag: latest

namespace: preview
