apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../coit-frontend

replicas:
- name: coit-frontend 
  count: 4

images:
- name: coitlearning/coit-frontend
  newName: coitlearning/coit-frontend
  newTag: '9'

namespace: staging
