apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: coit-frontend
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: 9676164428/coit-frontend:v15
          env:
            - name: COIT_BACKEND_URL
              value: "http://coit-backend1.102.12.12.45.sslip.io"
          ports:
            - containerPort: 80
              protocol: TCP 
