
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-fast
parameters:
  type: pd-ssd
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
