# This is a basic workflow to help you get started with Actions

name: CI for coit-frontend

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  buildandpush:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker login -u 9676164428 -p Valli@23..

      - name: Build the container Image
        run: | 
          docker build coit-simple-microservice/coit-frontend -t 9676164428/coit-frontend:latest -f coit-simple-microservice/coit-frontend/Dockerfile-multistage

      - name: Push the container Image
        run: | 
          docker push 9676164428/coit-frontend:latest

      
          
