name: CI for coit-frontend
'on':
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch: null
env:
  sonarscannerversion: 4.7.0.2747-linux
  PROJECT_ID: '${{ secrets.GKE_PROJECT }}'
  GKE_CLUSTER: githubactions
  GKE_ZONE: us-central1-c
  sonarqube_project: '${{ secrets.SONARQUBE_PROJECT }}'
  api_key: '${{ secrets.API_KEY }}'
  sonarqube_url: '${{ secrets.SONARQUBE_URL }}'
jobs:
  buildandpush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Sonar-Scanner
        run: >
          wget
          "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$sonarscannerversion.zip"

          unzip sonar-scanner-cli-$sonarscannerversion.zip -d $HOME/sonarqube

          chmod 755
          $HOME/sonarqube/sonar-scanner-$sonarscannerversion/bin/sonar-scanner
      - name: Scan the frontend project
        run: >
          cd coit-frontend

          $HOME/sonarqube/sonar-scanner-$sonarscannerversion/bin/sonar-scanner 
          \
            -Dsonar.projectKey=$sonarqube_project \
            -Dsonar.sources=. \
            -Dsonar.host.url=$sonarqube_url \
            -Dsonar.login=$api_key 
      - name: Run Unit Tests
        run: |
          cd coit-frontend
          npm test || true
      - name: Check the Vulnaribilities of Dependencies
        run: |
          cd coit-frontend
          npm audit || true
      - name: Docker Login
        env:
          DOCKERHUB_PASSWORD: '${{ secrets.DOCKERHUB_PASSWORD }}'
          DOCKERHUB_USERNAME: '${{ secrets.DOCKERHUB_USERNAME }}'
        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - name: Build the container Image
        run: | 
          docker build coit-frontend -t 9676164428/coit-frontend:v1 -f coit-frontend/Dockerfile-multistage
          docker build coit-backend1 -t 9676164428/sumaimagejava2:v1 -f coit-backend1/Dockerfile-multistage
          docker build coit-backend2 -t 9676164428/sumapython:v1 -f coit-backend2/Dockerfile
      - name: Push the container Image
        run: | 
          docker push 9676164428/coit-frontend:v1
          docker push 9676164428/sumaimagejava2:v1
          docker push 9676164428/sumapython:v1


      - uses: >-
          google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: '${{ secrets.GKE_SA_KEY }}'
          project_id: '${{ secrets.GKE_PROJECT }}'
      - uses: >-
          google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          location: '${{ env.GKE_ZONE }}'
          credentials: '${{ secrets.GKE_SA_KEY }}'
      - name: Deploy the GKE Cluster
        run: |
          cd kustomize/environments/preview
          kubectl apply -k .
      - name: Check the sonarqube report here
        run: | 
          SONAR_URL=`kubectl get svc sonarqube-sonarqube --output jsonpath='{.status.loadBalancer.ingress[0].ip}' -n sonarqube`
          echo "The SonarQube Reports are available at $SONAR_URL"
      - name: Wait for 60 seconds and get the preview of the applicaton
        run: | 
          sleep 60
          PRIVEW_URL=`kubectl get svc coit-frontend --output jsonpath='{.status.loadBalancer.ingress[0].ip}' -n suma`
          echo "This is app preview URL $PRIVEW_URL"
      
      # - name: Delete preview namespace
      #   run: | 
      #   sleep 15m
      #   kubectl delete namespace preview

