name: Deploy to production
on:
  create:
    tags:
     - 'v*'

env:
  sonarscannerversion: 4.7.0.2747-linux
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-1    # Add your cluster name here.
  GKE_ZONE: asia-south1-a   # Add your cluster zone here.

jobs:
  buildandpush:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      - name: Build the container Image
        run: | 
          docker build coit-frontend -t coitlearning/coit-frontend:$GITHUB_REF -f coit-frontend/Dockerfile-multistage

      - name: Push the container Image
        run: | 
          docker push coitlearning/coit-frontend:$GITHUB_REF

      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Deploy the GKE Cluster 
        run: | 
          cd kustomize/environments/preview
          kubectl apply -k .
